# Generated by Django 4.1.7 on 2023-03-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
