# Generated by Django 4.1.7 on 2023-04-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_with',
            field=models.ManyToManyField(blank=True, related_name='featured_songs', to='artist_card.artist', verbose_name='Участники'),
        ),
    ]
