# Generated by Django 4.1.7 on 2023-03-07 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0002_alter_song_options_alter_song_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='length',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
