# Generated by Django 4.1.7 on 2023-03-08 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0003_remove_song_length_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Длительность'),
        ),
    ]
