# Generated by Django 4.1.7 on 2023-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0004_artist_alter_album_artist_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(upload_to='images/album/', verbose_name='Обложка альбома'),
        ),
    ]
