# Generated by Django 4.1.7 on 2023-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0004_artist_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playcounts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество прослушиваний'),
        ),
    ]
