# Generated by Django 4.1.7 on 2023-03-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0005_alter_album_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['release', 'track_number'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер песни в релизе'),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.FileField(upload_to='images/release/', verbose_name='Обложка')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_card.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['artist'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='song',
            name='release',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artist_card.release', verbose_name='Релиз'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('release', 'track_number')},
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
