# Generated by Django 4.1.7 on 2023-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0005_alter_song_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.PositiveBigIntegerField(verbose_name='Номер песни в альбоме'),
        ),
    ]
