# Generated by Django 4.1.7 on 2023-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0006_artist_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='listens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
