# Generated by Django 4.1.7 on 2023-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0006_alter_song_options_alter_song_track_number_release_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('album', 'Альбом'), ('mixtape', 'Микстейп'), ('ep', 'Епи'), ('single', 'Сингл')], default=1, max_length=12, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
