# Generated by Django 4.1.7 on 2023-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0006_alter_song_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['album', 'track_number'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер песни в альбоме'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'track_number')},
        ),
        migrations.RemoveField(
            model_name='song',
            name='key',
        ),
    ]
