# Generated by Django 4.1.7 on 2023-03-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0007_release_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['pk'], 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('album', 'Альбом'), ('mixtape', 'Микстейп'), ('ep', 'Епи'), ('single', 'Сингл')], max_length=12, verbose_name='Тип релиза'),
        ),
    ]
