# Generated by Django 4.1.7 on 2023-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0008_alter_release_listens'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='featuring',
            field=models.CharField(blank=True, max_length=100, verbose_name='При участии'),
        ),
    ]
