# Generated by Django 4.1.7 on 2023-04-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0008_alter_artist_options_alter_release_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['artist'], 'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
    ]
