# Generated by Django 4.1.7 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0009_artist_featuring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='featuring',
        ),
        migrations.AddField(
            model_name='song',
            name='featuring',
            field=models.CharField(blank=True, max_length=100, verbose_name='При участии'),
        ),
    ]
