# Generated by Django 4.1.7 on 2023-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0011_remove_song_featuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featuring',
            field=models.CharField(blank=True, max_length=100, verbose_name='При участии'),
        ),
    ]
