# Generated by Django 4.1.7 on 2023-05-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0012_song_featuring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['artist'], 'verbose_name': 'Release', 'verbose_name_plural': 'Releases'},
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('released', 'Выпущен'), ('awaiting_upload', 'Ожидает выгрузки'), ('archived', 'В архиве'), ('in_progress', 'В работе')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_card.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='release',
            name='listens',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of listens'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('album', 'Album'), ('mixtape', 'Mixtape'), ('ep', 'EP'), ('single', 'Single')], max_length=12, verbose_name='Release type'),
        ),
    ]
