# Generated by Django 4.1.7 on 2023-05-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0013_alter_release_options_release_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['artist'], 'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
        migrations.RemoveField(
            model_name='release',
            name='status',
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_card.artist', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='release',
            name='listens',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('album', 'Альбом'), ('mixtape', 'Микстейп'), ('ep', 'Епи'), ('single', 'Сингл')], max_length=12, verbose_name='Тип релиза'),
        ),
    ]
