# Generated by Django 4.1.7 on 2023-05-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0015_release_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='status',
        ),
    ]
