# Generated by Django 4.1.7 on 2023-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0017_release_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('released', 'Выпущен на площадки'), ('awaiting_upload', 'Ожидает выгрузки'), ('archived', 'Архивирован'), ('in_progress', 'В работе')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
