# Generated by Django 4.1.7 on 2023-05-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0018_alter_release_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile_image',
        ),
    ]
