# Generated by Django 4.1.7 on 2023-04-14 21:37

from django.db import migrations
import sonichaven.models
from django.contrib.auth.models import Group


def create_artist_group(apps, schema_editor):
    artist_group = Group.objects.create(name='Artist')


class Migration(migrations.Migration):

    dependencies = [
        ('sonichaven', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', sonichaven.models.UserManager()),
            ],
        ),
        migrations.RunPython(create_artist_group),
    ]
