# Generated by Django 4.1.7 on 2023-05-30 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonichaven', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть формата +7 (XXX) XXX XX XX', regex='^\\+{1}[7]{1}\\s{1}\\(\\d{3}\\)\\s{1}\\d{3}\\s{1}\\d{2}\\s{1}\\d{2}$')], verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages', verbose_name='Фотография профиля'),
        ),
    ]
