# Generated by Django 4.1.7 on 2023-03-13 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist_card', '0004_artist_alter_album_artist_alter_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('type', models.CharField(choices=[('C', 'Композиция'), ('P', 'Производство'), ('M', 'Сведение'), ('M+', 'Сведение и Мастеринг'), ('D', 'Дистрибуция')], max_length=2, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='SoundDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Псеводним')),
                ('sex', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('O', 'Другое')], max_length=1, verbose_name='Пол')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='artist_card.artist', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='staff_service.shopcart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_service.service')),
            ],
            options={
                'verbose_name': 'Позиция в корзине',
                'verbose_name_plural': 'Позиции в корзине',
            },
        ),
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Длительность')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('format', models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3')], max_length=3, verbose_name='Формат')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='artist_card.artist')),
            ],
        ),
    ]
