# Generated by Django 4.1.7 on 2023-03-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='arrangement',
            options={'verbose_name': 'Арранжировка', 'verbose_name_plural': 'Арранжировки'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='sounddesigner',
            options={'verbose_name': 'Звукоржессер', 'verbose_name_plural': 'Звукоржессеры'},
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='staff_service.sounddesigner', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='format',
            field=models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('flac', 'FLAC'), ('aac', 'AAC'), ('dsd', 'DSD')], max_length=4, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='staff_service.genre'),
        ),
    ]
