# Generated by Django 4.1.7 on 2023-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounddesigner',
            name='services',
            field=models.ManyToManyField(to='staff_service.service', verbose_name='Услуги'),
        ),
    ]
