# Generated by Django 4.1.7 on 2023-03-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0002_alter_sounddesigner_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_service.service', verbose_name='Услуга'),
        ),
    ]
