# Generated by Django 4.1.7 on 2023-04-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0002_alter_manager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='staff_service.soundengineer', verbose_name='Автор'),
        ),
    ]
