# Generated by Django 4.1.7 on 2023-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0002_genre_alter_arrangement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость (RUB)'),
        ),
        migrations.AlterField(
            model_name='sounddesigner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='sounddesigner',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], max_length=1, verbose_name='Пол'),
        ),
    ]
