# Generated by Django 4.1.7 on 2023-03-15 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_service', '0003_alter_cartitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sounddesigner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sounddesigner_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
