# Generated by Django 4.1.7 on 2023-04-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0004_remove_cartitem_cart_shopcart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='staff_service.shopcart'),
            preserve_default=False,
        ),
    ]
