# Generated by Django 4.1.7 on 2023-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0004_alter_soundengineer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Exclusive', 'Эксклюзив'), ('Leasing', 'Базовый лизинг'), ('Leasing+', 'Коммерческий лизинг'), ('Key', 'Под ключ'), ('Production', 'Продакшн музыка'), ('Mixing', 'Сведение'), ('Mixing+', 'Сведение и Мастеринг'), ('Distribution', 'Дистрибуция'), ('Record', 'Запись')], max_length=12, verbose_name='Тип'),
        ),
    ]
