# Generated by Django 4.1.7 on 2023-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0004_alter_genre_options_remove_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('C', 'Композиция'), ('P', 'Производство'), ('M', 'Сведение'), ('M+', 'Сведение и Мастеринг'), ('D', 'Дистрибуция')], default=1, max_length=2, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
