# Generated by Django 4.1.7 on 2023-03-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0008_alter_artist_options_alter_release_image_and_more'),
        ('staff_service', '0006_sounddesigner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_terms', models.TextField()),
                ('signing_date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Длительность контракта в месяцах')),
                ('artist_signature', models.TextField(blank=True, null=True)),
                ('studio_admin_signature', models.TextField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_card.artist')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
