# Generated by Django 4.1.7 on 2023-04-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0006_remove_order_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа'),
        ),
    ]
