# Generated by Django 4.1.7 on 2023-03-21 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_card', '0008_alter_artist_options_alter_release_image_and_more'),
        ('staff_service', '0007_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='artist_signature',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='studio_admin_signature',
        ),
        migrations.AddField(
            model_name='contract',
            name='artist_signed',
            field=models.BooleanField(default=False, verbose_name='Подпись артиста'),
        ),
        migrations.AddField(
            model_name='contract',
            name='studio_admin_signed',
            field=models.BooleanField(default=False, verbose_name='Подпись администратора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_card.artist', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_terms',
            field=models.TextField(verbose_name='Условия контракта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration',
            field=models.PositiveIntegerField(help_text='Длительность контракта в месяцах', verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signing_date',
            field=models.DateField(verbose_name='Дата подписания'),
        ),
    ]
