# Generated by Django 4.1.7 on 2023-04-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0010_alter_manager_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='title',
        ),
    ]
