# Generated by Django 4.1.7 on 2023-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('royalty', 'Royalty'), ('fix_royalty', 'Fix + Royalty'), ('fix_only', 'Fix Only'), ('only_distribution', 'Only Distribution'), ('only_services', 'Only Services'), ('services_distribution', 'Services + Distribution')], default=1, max_length=21, verbose_name='Тип контракта'),
            preserve_default=False,
        ),
    ]
