# Generated by Django 4.1.7 on 2023-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_service', '0013_contract_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('percent', 'Процент'), ('fix_percent', 'Фиксированная + процент'), ('fix_only', 'Только фиксированная'), ('only_distribution', 'Только дистрибуция'), ('only_services', 'Только услуги'), ('services_distribution', 'Услуги + дистрибуция')], max_length=21, verbose_name='Тип контракта'),
        ),
    ]
