# Generated by Django 4.1.7 on 2023-03-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0002_newsarticle_remove_news_content_delete_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Абзац', 'verbose_name_plural': 'Абзацы'},
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='caption',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news_blog.news', verbose_name='Новость'),
        ),
    ]
