# Generated by Django 4.1.7 on 2023-03-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0003_alter_newsarticle_options_alter_newsarticle_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['id'], 'verbose_name': 'Абзац', 'verbose_name_plural': 'Абзацы'},
        ),
    ]
