# Generated by Django 4.1.7 on 2023-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0004_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/news_article/', verbose_name='Изображение'),
        ),
    ]
